# Generated by Django 4.2.13 on 2024-06-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RelationshipData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity1_parent", models.CharField(max_length=100)),
                ("entity1", models.CharField(max_length=50)),
                ("entity1_type", models.CharField(max_length=50)),
                ("entity2_parent", models.CharField(max_length=100)),
                ("entity2", models.CharField(max_length=50)),
                ("entity2_type", models.CharField(max_length=50)),
                ("relationship", models.CharField(max_length=50)),
            ],
        ),
    ]
